Remove section for retrying after timeouts

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -44,7 +44,6 @@ runs:
         ENV_KEYVAULT_NAME="${{ inputs.environmentKeyVault }}"
         CONTENT_TYPES="${{ inputs.contentTypes }}"
         EXCLUDE_CONTENT_TYPES="${{ inputs.excludeContentTypes }}"
-        FILE="${{ github.workspace }}/.env"
 
         # If ENV_KEYVAULT_NAME is empty, search for key vault using tags
         if [ -n "${ENV_KEYVAULT_NAME}" ]; then
@@ -53,7 +52,30 @@ runs:
         else
             # Search for key vault using tags
             echo -e "Searching for key vault with tags: \"repository-name=${REPOSITORY_NAME};environment=${ENVIRONMENT}\""
-            KEYVAULT_NAME=$(az keyvault list --query "[?tags.\"repository-name\" == '${REPOSITORY_NAME}' && tags.environment == '${ENVIRONMENT}'].name" --output tsv)
+
+            # Initialize a counter
+            COUNTER=1
+
+            # Try the command up to 5 times
+            while [[ "${COUNTER}" -lt 6 ]]; do
+                # Break loop if command is successful
+                if KEYVAULT_NAME=$(az keyvault list --query "[?tags.\"repository-name\" == '${REPOSITORY_NAME}' && tags.environment == '${ENVIRONMENT}'].name" --output tsv); then
+                    break
+                fi
+
+                # Display retry attempt and increment the COUNTER
+                echo -e "Retrieval of the key vault failed on attempt ${COUNTER} of 5. Waiting 5 seconds before trying again."
+                COUNTER=$((COUNTER+1))
+
+                # Exit with error after 5 failed attempts
+                if [[ "${COUNTER}" -eq 6 ]]; then
+                    echo -e "Failed to list key vaults after 5 attempts. Please confirm this repository's key vaults are tagged correctly."
+                    exit 1
+                fi
+
+                # Pause before next attempt
+                sleep 5
+            done
         fi
 
         # Get key vault object
@@ -90,7 +112,7 @@ runs:
         done
         SECRETS=("${SECRET_LIST[@]}")
 
-        # Loop through secrets and add them to ${FILE}
+        # Loop through secrets and add them to .env file
         echo "Retrieving secrets for key vault: ${KEYVAULT_NAME}"
         if echo "${SECRETS[*]}" | grep -E "\w" > /dev/null; then
             for SECRET in "${SECRETS[@]}"; do
@@ -114,12 +136,12 @@ runs:
                     fi
                     if [[ "${SECRET_CONTENT_TYPE}" =~ "Env" ]] || [[ "${SECRET_CONTENT_TYPE}" =~ "Key" ]]; then
                         ENVIRONMENT_VARIABLES+="${SECRET_NAME}=${SECRET_VALUE} "
-                        echo "${SECRET_NAME}=${SECRET_VALUE}" >> ${FILE}
+                        echo "${SECRET_NAME}=${SECRET_VALUE}" >> "${{ github.workspace }}/.env"
                     fi
                 fi
             done
         else
-            echo "" >> ${FILE}
+            echo "" >> "${{ github.workspace }}/.env"
         fi
 
         if [[ "${CONTENT_TYPES}" == *"BuildArg"* ]]; then
